name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            compiler: dmd-master
          - os: ubuntu-latest 
            arch: amd64
            compiler: ldc-latest
          - os: ubuntu-24.04-arm 
            arch: arm64
            compiler: ldc-latest
          - os: macos-latest
            arch: arm64
            compiler: ldc-latest
          - os: windows-latest
            arch: amd64
            compiler: dmd-master
          - os: windows-latest
            arch: amd64
            compiler: ldc-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@main
      - uses: ai-action/setup-ollama@v2
        with:
          version: 0.17.6
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{matrix.compiler}}
      - name: unittests
        run: dub test
      - name: Build
        run: dub build -b release
      - name: Run simple client
        run: dub run -b release :simple
      - name: Run agent
        run: dub run -b release :agent -- "What is the current UTC time? Also, what is 123 plus 456?"
      - name: Run coder client
        run: dub run -b release :coder -- --prompt "Create a C function to sort an array" --model qwen3.5:9b --verbose
